import Foundation

nonisolated struct BuiltInQuestions {
    static let friendsFamily: [String] = [
        "What's one decision you've made that completely changed the course of your life?",
        "What does being a good friend mean to you?",
        "Something in my personality that you really like?",
        "How do you usually handle disagreements and conflicts in your relationships?",
        "Was there a moment in your past you wish you could relive — not to change, but to feel again?",
        "What was your first impression of me when we first met?",
        "Which friend do you feel has a personality most similar to yours?",
        "Who was your biggest role model growing up, and why?",
        "What is something you did that you later regretted?",
        "How do you want to be remembered?",
        "Do you see yourself as someone who enjoys solitude and being alone, or are you more social?",
        "What is the place you love going to the most?",
        "Where do you see yourself ten years from now?",
        "Do you have the courage to admit a mistake you made in your life?",
        "What are your positive qualities?",
        "Who is the person you miss the most right now?",
        "Have you ever told someone a secret and later regretted it?",
        "How many times have you been in love in your life?",
        "What is one mistake you could never forgive if someone did it to you?",
        "Are you satisfied with your appearance and your weight?",
        "Have you ever witnessed a situation involving bullying? How did you react?",
        "If you had to choose between living in a quiet city or a crowded city, which would you choose?",
        "If someone wronged your friend and your friend was actually in the wrong, would you still defend your friend or let them face it alone?",
        "What is your favorite memory we have together?",
        "Imagine you won the biggest lottery prize — what's the first thing you would do?",
        "Is there a situation where you behaved badly and wish you could go back in time to fix it?",
        "What is the ideal life you would like to live?",
        "If you went back in time and met your younger self, would they like the person you've become?",
        "How do you make yourself happy when you're going through deep disappointment?",
        "If there is one piece of advice you would give, what would it be?",
        "How do you approach making amends when you've hurt someone?",
        "How do you balance being honest about your feelings with being considerate of others?",
        "How do you practice self-care and maintain your mental health?",
        "How do you typically handle stress or difficult emotions?",
        "What's a compliment you have difficulty accepting, and why?",
        "What habit or behavior are you trying to change about yourself?",
        "What's a misconception people often have about you?",
        "What's a personal boundary you've had to set, and how did it affect your relationships?",
        "What's a personal insecurity you're working on overcoming?",
        "What personal strength are you proud of, and how did you develop it?"
    ]
    
    static let couple: [String] = [
        "Is there something you've always wanted to tell me but haven't found the right moment?",
        "If our love story was a book, what would the title be?",
        "What's one thing about our relationship that feels rare or special to you?",
        "When did you first realize you loved me?",
        "How do you prefer to receive and express love?",
        "What's something you've learned about yourself through our relationship?",
        "What's a challenging aspect of our relationship that you think we need to work on?",
        "What's your approach to handling conflicts in our relationship?",
        "How do you envision our ideal future together?",
        "What's a place you'd like us to live in or visit together in the future?",
        "What long-term goal would you like us to work towards as a couple?",
        "What's a new skill or hobby you'd like us to learn together?",
        "What's a romantic gesture that means a lot to you?",
        "How do you think we can maintain intimacy during challenging times?",
        "What do you appreciate most about the way we communicate?"
    ]
}
